<a href="https://colab.research.google.com/github/IrisMeng9/data_science/blob/main/w2_hw.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Part 1 - Numpy


1. Define two custom numpy arrays, say A and B. Generate two new numpy arrays by stacking A and B vertically and horizontally.


In [1]:
import numpy as np
import pandas as pd

In [8]:
A = np.array([1, 2, 3, 4])
B = np.array([4, 6, 7, 8])

# stacking vertically
C = np.vstack([A,B])
print(C)

[[1 2 3 4]
 [4 6 7 8]]


In [9]:
C.shape

(2, 4)

In [10]:
# stack horizontally
D = np.hstack([A, B])
print(D)

[1 2 3 4 4 6 7 8]


In [11]:
D.shape

(8,)

2. ⁠Find common elements between A and B. [Hint : Intersection of two sets]

In [12]:
np.intersect1d(A,B)

array([4])

3. Extract all numbers from A which are within a specific range. eg between 5 and 10. [Hint: np.where() might be useful or boolean masks]

In [17]:
A_2 = A[(A > 5) & (A < 10)]
print(A_2)

[]


The result array is empty cause there is **no** number within the specified range.

Use this dataset for the first 4 questions.

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

4.⁠ Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0

In [18]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])


In [19]:
iris_2d.shape

(150, 4)

In [25]:
ind = np.where((iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0))
filtered = iris_2d[ind]
filtered

array([[4.8, 3.4, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7]])

In [28]:
filtered.shape
print(f"There are {filtered.shape[0]} rows of data that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0")

There are 6 rows of data that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0


### Optional Practice Question


In [51]:
#Find the mean of a numeric column grouped by a categorical column in a 2D numpy array

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

numeric_column = iris[:, 1].astype('float')  # sepalwidth
grouping_column = iris[:, 4]  # species

In [52]:
output = []
"""Your code goes here"""
# find unique group names and their corresponding index
unique_group, index = np.unique(grouping_column, return_inverse=True)
unique_group

array([b'Iris-setosa', b'Iris-versicolor', b'Iris-virginica'],
      dtype=object)

In [53]:
for i in range(len(unique_group)):
  mean = numeric_column[index == i].mean()
  output.append(mean)
  print(f"The mean of {unique_group[i]} is {mean}")

The mean of b'Iris-setosa' is 3.418
The mean of b'Iris-versicolor' is 2.7700000000000005
The mean of b'Iris-virginica' is 2.974


In [54]:
print(output)

[3.418, 2.7700000000000005, 2.974]


## Part 2 - Pandas

1. ⁠From df filter the 'Manufacturer', 'Model' and 'Type' for every 20th row starting from 1st (row 0).



In [29]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

In [55]:
df.head()

Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0        Acura  Integra    Small       12.9   15.9       18.8      25.0   
1          NaN   Legend  Midsize       29.2   33.9       38.7      18.0   
2         Audi       90  Compact       25.9   29.1       32.3      20.0   
3         Audi      100  Midsize        NaN   37.7       44.6      19.0   
4          BMW     535i  Midsize        NaN   30.0        NaN      22.0   

   MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0         31.0                 NaN      Front  ...        5.0   177.0   
1         25.0  Driver & Passenger      Front  ...        5.0   195.0   
2         26.0         Driver only      Front  ...        5.0   180.0   
3         26.0  Driver & Passenger        NaN  ...        6.0   193.0   
4         30.0                 NaN       Rear  ...        4.0   186.0   

   Wheelbase  Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \
0      102.0   68.0         37.0           26.5           NaN  2705.0   
1      115.0   71.0         38.0           30.0          15.0  3560.0   
2      102.0   67.0         37.0           28.0          14.0  3375.0   
3      106.0    NaN         37.0           31.0          17.0  3405.0   
4      109.0   69.0         39.0           27.0          13.0  3640.0   

    Origin           Make  
0  non-USA  Acura Integra  
1  non-USA   Acura Legend  
2  non-USA        Audi 90  
3  non-USA       Audi 100  
4  non-USA       BMW 535i  

[5 rows x 27 columns]

In [60]:
df[['Manufacturer','Model', 'Type']][::20]

Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small

2.⁠ ⁠Replace missing values in Min.Price and Max.Price columns with their respective mean.

df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')



In [61]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93 entries, 0 to 92
Data columns (total 27 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Manufacturer        89 non-null     object 
 1   Model               92 non-null     object 
 2   Type                90 non-null     object 
 3   Min.Price           86 non-null     float64
 4   Price               91 non-null     float64
 5   Max.Price           88 non-null     float64
 6   MPG.city            84 non-null     float64
 7   MPG.highway         91 non-null     float64
 8   AirBags             55 non-null     object 
 9   DriveTrain          86 non-null     object 
 10  Cylinders           88 non-null     object 
 11  EngineSize          91 non-null     float64
 12  Horsepower          86 non-null     float64
 13  RPM                 90 non-null     float64
 14  Rev.per.mile        87 non-null     float64
 15  Man.trans.avail     88 non-null     object 
 16  Fuel.tank.

In [64]:
df['Min.Price'] = df['Min.Price'].fillna(df['Min.Price'].mean())
df['Max.Price'] = df['Max.Price'].fillna(df['Max.Price'].mean())
print(f"The NA values of Min.Pirce is {df['Min.Price'].isna().sum()}")
print(f"The NA values of Max.Pirce is {df['Max.Price'].isna().sum()}")

The NA values of Min.Pirce is 0
The NA values of Max.Pirce is 0


3. ⁠How to get the rows of a dataframe with row sum > 100?

df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))

In [69]:
df_3 = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))
df_3

0   1   2   3
0   28  39  32  34
1   27  15  36  32
2   32  17  26  17
3   35  25  18  31
4   21  15  20  26
5   10  32  30  25
6   37  19  26  32
7   38  29  36  21
8   30  37  31  23
9   10  14  10  11
10  36  27  33  32
11  13  36  11  10
12  27  18  22  28
13  36  22  22  21
14  29  38  23  34

In [72]:
# find the sum of each row that is > 100
df_3[df_3.sum(axis=1) > 100]

0   1   2   3
0   28  39  32  34
1   27  15  36  32
3   35  25  18  31
6   37  19  26  32
7   38  29  36  21
8   30  37  31  23
10  36  27  33  32
13  36  22  22  21
14  29  38  23  34